# Generated by Django 4.1 on 2022-11-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 11, 19, 9, 32, 15, 16114, tzinfo=datetime.timezone.utc)),
        ),
    ]
