# Generated by Django 4.1 on 2022-11-20 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 12, 23, 55, 433178, tzinfo=datetime.timezone.utc)),
        ),
    ]
