# Generated by Django 4.1 on 2022-11-05 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_created_date_alter_car_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 11, 5, 10, 59, 30, 144783, tzinfo=datetime.timezone.utc)),
        ),
    ]
