# Generated by Django 4.1 on 2022-11-05 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_created_date_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 11, 5, 16, 42, 15, 583098, tzinfo=datetime.timezone.utc)),
        ),
    ]
