# Generated by Django 4.1 on 2022-11-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 11, 19, 9, 32, 14, 864905, tzinfo=datetime.timezone.utc)),
        ),
    ]
